export type SeverityLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type ResponseClass = 'LOG_ONLY' | 'ALERT_ADMIN' | 'REQUIRE_STEP_UP_AUTHENTICATION' | 'TEMPORARY_RATE_LIMIT' | 'FREEZE_HIGH_RISK_WORKFLOW' | 'REQUIRE_HUMAN_REVIEW';
export type EventSourceType = 'AuthenticationSecurityLog' | 'PaymentWebhookLog' | 'PaymentActionLog' | 'ApiSecurityLog' | 'AIBotLog' | 'SystemErrorLog' | 'AuditLog' | 'SecurityEvent';

export interface DetectionRule {
  RULE_ID: string;
  EVENT_TYPE: string;
  DESCRIPTION: string;
  SEVERITY: SeverityLevel;
  SOURCE_TYPES: EventSourceType[];
  THRESHOLD: number;
  TIME_WINDOW: number; // in milliseconds
  DEDUPLICATION_WINDOW: number; // in milliseconds
  COOLDOWN: number; // in milliseconds
  ENABLED: boolean;
  RESPONSE_CLASS: ResponseClass;
}

export const DetectionRegistry: DetectionRule[] = [
  // Authentication and Identity
  {
    RULE_ID: 'AUTH_FAILURE_THRESHOLD_DETECTED',
    EVENT_TYPE: 'AUTH_FAILURE_BURST',
    DESCRIPTION: 'Detects bursts of authentication failures indicating brute-force or credential stuffing.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['AuthenticationSecurityLog'],
    THRESHOLD: 5,
    TIME_WINDOW: 60000,
    DEDUPLICATION_WINDOW: 300000,
    COOLDOWN: 300000,
    ENABLED: true,
    RESPONSE_CLASS: 'REQUIRE_STEP_UP_AUTHENTICATION',
  },
  {
    RULE_ID: 'CREDENTIAL_STUFFING_PATTERN',
    EVENT_TYPE: 'CREDENTIAL_STUFFING',
    DESCRIPTION: 'Multiple accounts accessed from same source in short time.',
    SEVERITY: 'CRITICAL',
    SOURCE_TYPES: ['AuthenticationSecurityLog'],
    THRESHOLD: 10,
    TIME_WINDOW: 300000,
    DEDUPLICATION_WINDOW: 600000,
    COOLDOWN: 600000,
    ENABLED: true,
    RESPONSE_CLASS: 'FREEZE_HIGH_RISK_WORKFLOW',
  },
  {
    RULE_ID: 'ACCOUNT_ENUMERATION_PATTERN',
    EVENT_TYPE: 'ACCOUNT_ENUMERATION',
    DESCRIPTION: 'Multiple failed attempts on non-existent accounts.',
    SEVERITY: 'MEDIUM',
    SOURCE_TYPES: ['AuthenticationSecurityLog'],
    THRESHOLD: 20,
    TIME_WINDOW: 60000,
    DEDUPLICATION_WINDOW: 300000,
    COOLDOWN: 300000,
    ENABLED: true,
    RESPONSE_CLASS: 'TEMPORARY_RATE_LIMIT',
  },
  {
    RULE_ID: 'SESSION_REPLAY_OR_TOKEN_REUSE',
    EVENT_TYPE: 'SESSION_REPLAY',
    DESCRIPTION: 'Reused or invalid session tokens detected.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['AuthenticationSecurityLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 10000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'REQUIRE_STEP_UP_AUTHENTICATION',
  },
  {
    RULE_ID: 'MULTIPLE_ACCOUNT_LOCKOUTS_FROM_ONE_SOURCE',
    EVENT_TYPE: 'SOURCE_LOCKOUT_BURST',
    DESCRIPTION: 'Multiple users locked out from single IP or Device.',
    SEVERITY: 'CRITICAL',
    SOURCE_TYPES: ['AuthenticationSecurityLog'],
    THRESHOLD: 3,
    TIME_WINDOW: 300000,
    DEDUPLICATION_WINDOW: 900000,
    COOLDOWN: 900000,
    ENABLED: true,
    RESPONSE_CLASS: 'ALERT_ADMIN',
  },
  {
    RULE_ID: 'IDENTITY_VERIFICATION_FAILURE_BURST',
    EVENT_TYPE: 'KYC_FAILURE_BURST',
    DESCRIPTION: 'Repeated KYC failures indicative of identity fraud.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['AuditLog'],
    THRESHOLD: 3,
    TIME_WINDOW: 86400000,
    DEDUPLICATION_WINDOW: 86400000,
    COOLDOWN: 86400000,
    ENABLED: true,
    RESPONSE_CLASS: 'REQUIRE_HUMAN_REVIEW',
  },

  // Authorization and administrative abuse
  {
    RULE_ID: 'PRIVILEGE_ESCALATION_DETECTED',
    EVENT_TYPE: 'PRIVILEGE_ESCALATION_ATTEMPT',
    DESCRIPTION: 'Attempt to execute actions above authorized role.',
    SEVERITY: 'CRITICAL',
    SOURCE_TYPES: ['ApiSecurityLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'ALERT_ADMIN',
  },
  {
    RULE_ID: 'UNAUTHORIZED_ADMIN_ROUTE_ACCESS',
    EVENT_TYPE: 'ADMIN_ROUTE_BYPASS_ATTEMPT',
    DESCRIPTION: 'Non-admin attempting to access admin routes.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['ApiSecurityLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'ALERT_ADMIN',
  },
  {
    RULE_ID: 'ROLE_OR_PERMISSION_CHANGE',
    EVENT_TYPE: 'ADMIN_ROLE_CHANGE',
    DESCRIPTION: 'Change of user role or permissions.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['AuditLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'REQUIRE_HUMAN_REVIEW',
  },
  {
    RULE_ID: 'EMERGENCY_FREEZE_BYPASS_DETECTED',
    EVENT_TYPE: 'EMERGENCY_FREEZE_BYPASS_ATTEMPT',
    DESCRIPTION: 'Attempt to bypass or disable emergency freeze without authorization.',
    SEVERITY: 'CRITICAL',
    SOURCE_TYPES: ['ApiSecurityLog', 'AuditLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'ALERT_ADMIN',
  },
  {
    RULE_ID: 'SECURITY_SETTING_CHANGE',
    EVENT_TYPE: 'SECURITY_SETTING_MODIFIED',
    DESCRIPTION: 'Global security setting modification.',
    SEVERITY: 'CRITICAL',
    SOURCE_TYPES: ['AuditLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'ALERT_ADMIN',
  },
  {
    RULE_ID: 'EVENT_INGESTION_FAILURE_FAILS_SAFELY',
    EVENT_TYPE: 'AUDIT_LOGGING_FAILURE',
    DESCRIPTION: 'Failures in the audit logging or security event ingestion pipeline.',
    SEVERITY: 'CRITICAL',
    SOURCE_TYPES: ['SystemErrorLog'],
    THRESHOLD: 5,
    TIME_WINDOW: 60000,
    DEDUPLICATION_WINDOW: 300000,
    COOLDOWN: 300000,
    ENABLED: true,
    RESPONSE_CLASS: 'ALERT_ADMIN',
  },

  // Payment and Escrow
  {
    RULE_ID: 'WEBHOOK_REPLAY_DETECTED',
    EVENT_TYPE: 'WEBHOOK_FAIL',
    DESCRIPTION: 'Replayed payment webhook signatures detected.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['PaymentWebhookLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'LOG_ONLY',
  },
  {
    RULE_ID: 'WEBHOOK_SIGNATURE_FAILURE_BURST',
    EVENT_TYPE: 'WEBHOOK_SIGNATURE_FAILURE',
    DESCRIPTION: 'Repeated webhook signature verification failures.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['PaymentWebhookLog'],
    THRESHOLD: 5,
    TIME_WINDOW: 60000,
    DEDUPLICATION_WINDOW: 300000,
    COOLDOWN: 300000,
    ENABLED: true,
    RESPONSE_CLASS: 'ALERT_ADMIN',
  },
  {
    RULE_ID: 'PAYMENT_STATE_TAMPERING_DETECTED',
    EVENT_TYPE: 'PAYMENT_STATE_TRANSITION_REJECTED',
    DESCRIPTION: 'Invalid state transition attempted on a payment.',
    SEVERITY: 'CRITICAL',
    SOURCE_TYPES: ['PaymentActionLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'FREEZE_HIGH_RISK_WORKFLOW',
  },
  {
    RULE_ID: 'PAYMENT_RECONCILIATION_MISMATCH',
    EVENT_TYPE: 'PAYMENT_RECONCILIATION_FAILED',
    DESCRIPTION: 'Mismatch between expected and received gateway funds.',
    SEVERITY: 'CRITICAL',
    SOURCE_TYPES: ['PaymentReconciliationLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 3600000,
    COOLDOWN: 3600000,
    ENABLED: true,
    RESPONSE_CLASS: 'REQUIRE_HUMAN_REVIEW',
  },
  {
    RULE_ID: 'DUPLICATE_CAPTURE_ATTEMPT',
    EVENT_TYPE: 'DUPLICATE_PAYMENT_CAPTURE',
    DESCRIPTION: 'Attempt to capture payment more than once.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['PaymentActionLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'LOG_ONLY',
  },
  {
    RULE_ID: 'UNAUTHORIZED_REFUND_ATTEMPT',
    EVENT_TYPE: 'UNAUTHORIZED_REFUND',
    DESCRIPTION: 'Attempt to issue a refund without permissions.',
    SEVERITY: 'CRITICAL',
    SOURCE_TYPES: ['PaymentActionLog', 'ApiSecurityLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'ALERT_ADMIN',
  },
  {
    RULE_ID: 'UNAUTHORIZED_ESCROW_RELEASE_DETECTED',
    EVENT_TYPE: 'UNAUTHORIZED_ESCROW_RELEASE_ATTEMPT',
    DESCRIPTION: 'Attempt to release escrow without proper authorization or state.',
    SEVERITY: 'CRITICAL',
    SOURCE_TYPES: ['PaymentActionLog', 'ApiSecurityLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'ALERT_ADMIN',
  },

  // Marketplace Abuse
  {
    RULE_ID: 'BOOKING_CREATION_BURST',
    EVENT_TYPE: 'BOOKING_SPAM',
    DESCRIPTION: 'Unusually high booking rate from a single user.',
    SEVERITY: 'MEDIUM',
    SOURCE_TYPES: ['AuditLog'],
    THRESHOLD: 10,
    TIME_WINDOW: 300000,
    DEDUPLICATION_WINDOW: 900000,
    COOLDOWN: 900000,
    ENABLED: true,
    RESPONSE_CLASS: 'TEMPORARY_RATE_LIMIT',
  },
  {
    RULE_ID: 'LISTING_CREATION_BURST',
    EVENT_TYPE: 'LISTING_SPAM',
    DESCRIPTION: 'Unusually high listing creation rate from a single provider.',
    SEVERITY: 'MEDIUM',
    SOURCE_TYPES: ['AuditLog'],
    THRESHOLD: 20,
    TIME_WINDOW: 3600000,
    DEDUPLICATION_WINDOW: 7200000,
    COOLDOWN: 7200000,
    ENABLED: true,
    RESPONSE_CLASS: 'TEMPORARY_RATE_LIMIT',
  },
  {
    RULE_ID: 'REPEATED_DISPUTE_OR_CLAIM_PATTERN',
    EVENT_TYPE: 'ABUSIVE_DISPUTE_PATTERN',
    DESCRIPTION: 'User involved in multiple disputes or damage claims recently.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['AuditLog'],
    THRESHOLD: 3,
    TIME_WINDOW: 2592000000, // 30 days
    DEDUPLICATION_WINDOW: 604800000,
    COOLDOWN: 604800000,
    ENABLED: true,
    RESPONSE_CLASS: 'REQUIRE_HUMAN_REVIEW',
  },
  {
    RULE_ID: 'PROVIDER_VERIFICATION_ABUSE',
    EVENT_TYPE: 'VERIFICATION_ABUSE',
    DESCRIPTION: 'Excessive attempts to bypass provider verification.',
    SEVERITY: 'MEDIUM',
    SOURCE_TYPES: ['AuditLog'],
    THRESHOLD: 5,
    TIME_WINDOW: 86400000,
    DEDUPLICATION_WINDOW: 86400000,
    COOLDOWN: 86400000,
    ENABLED: true,
    RESPONSE_CLASS: 'REQUIRE_HUMAN_REVIEW',
  },
  {
    RULE_ID: 'CROSS_ACCOUNT_RESOURCE_ENUMERATION',
    EVENT_TYPE: 'CROSS_ACCOUNT_ENUMERATION',
    DESCRIPTION: 'Attempt to access multiple resources belonging to other tenants.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['ApiSecurityLog'],
    THRESHOLD: 5,
    TIME_WINDOW: 60000,
    DEDUPLICATION_WINDOW: 300000,
    COOLDOWN: 300000,
    ENABLED: true,
    RESPONSE_CLASS: 'ALERT_ADMIN',
  },

  // AI-Linked Detections
  {
    RULE_ID: 'DIRECT_PROMPT_INJECTION_BLOCKED',
    EVENT_TYPE: 'AI_PROMPT_INJECTION_DETECTED',
    DESCRIPTION: 'Direct attempt to inject or override prompt instructions.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['AIBotLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'LOG_ONLY',
  },
  {
    RULE_ID: 'INDIRECT_LISTING_INJECTION_BLOCKED',
    EVENT_TYPE: 'AI_INDIRECT_INJECTION_DETECTED',
    DESCRIPTION: 'Indirect prompt injection via listings or external data.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['AIBotLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'LOG_ONLY',
  },
  {
    RULE_ID: 'UNKNOWN_AI_ACTION_PROHIBITED',
    EVENT_TYPE: 'AI_UNAUTHORIZED_TOOL_ATTEMPT',
    DESCRIPTION: 'Attempt to use an unauthorized or unknown AI tool.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['AIBotLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'ALERT_ADMIN',
  },
  {
    RULE_ID: 'AI_HIGH_RISK_ACTION_ATTEMPT',
    EVENT_TYPE: 'AI_HIGH_RISK_ACTION_ATTEMPT',
    DESCRIPTION: 'AI attempting to execute a prohibited or human-approval-only action autonomously.',
    SEVERITY: 'CRITICAL',
    SOURCE_TYPES: ['AIBotLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'ALERT_ADMIN',
  },
  {
    RULE_ID: 'SENSITIVE_OUTPUT_REDACTED_OR_BLOCKED',
    EVENT_TYPE: 'AI_SENSITIVE_OUTPUT_BLOCKED',
    DESCRIPTION: 'AI generated response containing secrets or PII which was blocked.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['AIBotLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'LOG_ONLY',
  },
  {
    RULE_ID: 'CROSS_USER_RESOURCE_ACCESS_REJECTED',
    EVENT_TYPE: 'AI_CROSS_USER_ACCESS_ATTEMPT',
    DESCRIPTION: 'AI attempt to access another users resources.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['AIBotLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'ALERT_ADMIN',
  },
  {
    RULE_ID: 'TOOL_CALL_RATE_LIMIT_ENFORCED',
    EVENT_TYPE: 'AI_RATE_LIMIT_EXCEEDED',
    DESCRIPTION: 'User exceeded AI messaging or tool call limits.',
    SEVERITY: 'MEDIUM',
    SOURCE_TYPES: ['AIBotLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 300000,
    COOLDOWN: 300000,
    ENABLED: true,
    RESPONSE_CLASS: 'TEMPORARY_RATE_LIMIT',
  },
  {
    RULE_ID: 'AI_MODEL_OR_PROVIDER_FAILURE',
    EVENT_TYPE: 'AI_MODEL_OR_PROVIDER_FAILURE',
    DESCRIPTION: 'Failure communicating with AI provider.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['SystemErrorLog'],
    THRESHOLD: 5,
    TIME_WINDOW: 60000,
    DEDUPLICATION_WINDOW: 300000,
    COOLDOWN: 300000,
    ENABLED: true,
    RESPONSE_CLASS: 'ALERT_ADMIN',
  },
  {
    RULE_ID: 'SYSTEM_PROMPT_EXTRACTION_BLOCKED',
    EVENT_TYPE: 'AI_SYSTEM_PROMPT_EXTRACTION_ATTEMPT',
    DESCRIPTION: 'Attempt to extract the system prompt.',
    SEVERITY: 'HIGH',
    SOURCE_TYPES: ['AIBotLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'LOG_ONLY',
  },
  {
    RULE_ID: 'SECRET_REQUEST_BLOCKED',
    EVENT_TYPE: 'AI_SECRET_REQUEST_ATTEMPT',
    DESCRIPTION: 'Attempt to request API keys or database strings from AI.',
    SEVERITY: 'CRITICAL',
    SOURCE_TYPES: ['AIBotLog'],
    THRESHOLD: 1,
    TIME_WINDOW: 1000,
    DEDUPLICATION_WINDOW: 60000,
    COOLDOWN: 60000,
    ENABLED: true,
    RESPONSE_CLASS: 'ALERT_ADMIN',
  }
];
