/**
 * RENTipid GLCC v1.1 — Centralized Global Country Registry
 *
 * Work Package: GLOBAL-W1
 *
 * Implements:
 * 1. Normalized country profile catalog for all 15 owner-confirmed compliance jurisdictions:
 *    - 14 direct countries: PH, US, GB, CA, AU, SG, MY, ID, VN, JP, KR, IN, AE, BR
 *    - 30 individual EU/EEA member states mapped to complianceGroup: 'European Union / EEA'
 * 2. Country/Currency Independence:
 *    - Country suggests a defaultDisplayCurrency (e.g. PL suggests PLN, SE suggests SEK, JP suggests JPY).
 *    - Allowed display currencies include all globally active currencies.
 *    - Allowed charge currency is strictly locked to PHP.
 * 3. Country/Language Independence:
 *    - Country suggests defaultLanguageTag, but changing country does not mutate an explicit language preference.
 * 4. Integration with RENTipid Global Legal Compliance registry (ALL_REGISTERS).
 */

import type { CountryProfile } from '../registry-contracts';
import { GLOBAL_SUPPORTED_CURRENCY_CODES } from '../currency/currency-registry';

export interface GlobalCountryProfile extends CountryProfile {
  readonly complianceGroup: string;
  readonly regionCategory: 'APAC' | 'AMERICAS' | 'EMEA' | 'EU_EEA';
}

export const GLOBAL_COUNTRY_CATALOG: readonly GlobalCountryProfile[] = Object.freeze([
  // Direct Compliance Jurisdictions
  {
    code: 'PH',
    countryCode: 'PH',
    name: 'Philippines',
    complianceGroup: 'Philippines',
    regionCategory: 'APAC',
    defaultDisplayCurrency: 'PHP',
    defaultCurrency: 'PHP',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'en-PH',
    supportedLanguageTags: ['en-PH', 'fil-PH'],
    defaultTimezone: 'Asia/Manila',
    timezoneDefault: 'Asia/Manila',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'US',
    countryCode: 'US',
    name: 'United States',
    complianceGroup: 'United States',
    regionCategory: 'AMERICAS',
    defaultDisplayCurrency: 'USD',
    defaultCurrency: 'USD',
    allowedDisplayCurrencies: ['USD'],
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'en-US',
    supportedLanguageTags: ['en-US', 'es-ES'],
    defaultTimezone: 'America/New_York',
    timezoneDefault: 'America/New_York',
    unitSystem: 'imperial',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'GB',
    countryCode: 'GB',
    name: 'United Kingdom',
    complianceGroup: 'United Kingdom',
    regionCategory: 'EMEA',
    defaultDisplayCurrency: 'GBP',
    defaultCurrency: 'GBP',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'en-GB',
    supportedLanguageTags: ['en-GB'],
    defaultTimezone: 'Europe/London',
    timezoneDefault: 'Europe/London',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'CA',
    countryCode: 'CA',
    name: 'Canada',
    complianceGroup: 'Canada',
    regionCategory: 'AMERICAS',
    defaultDisplayCurrency: 'CAD',
    defaultCurrency: 'CAD',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'en-CA',
    supportedLanguageTags: ['en-CA', 'fr-CA', 'fr-FR'],
    defaultTimezone: 'America/Toronto',
    timezoneDefault: 'America/Toronto',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'AU',
    countryCode: 'AU',
    name: 'Australia',
    complianceGroup: 'Australia',
    regionCategory: 'APAC',
    defaultDisplayCurrency: 'AUD',
    defaultCurrency: 'AUD',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'en-AU',
    supportedLanguageTags: ['en-AU'],
    defaultTimezone: 'Australia/Sydney',
    timezoneDefault: 'Australia/Sydney',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'SG',
    countryCode: 'SG',
    name: 'Singapore',
    complianceGroup: 'Singapore',
    regionCategory: 'APAC',
    defaultDisplayCurrency: 'SGD',
    defaultCurrency: 'SGD',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'en-SG',
    supportedLanguageTags: ['en-SG', 'zh-Hans', 'ms-MY', 'ta-SG'],
    defaultTimezone: 'Asia/Singapore',
    timezoneDefault: 'Asia/Singapore',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'MY',
    countryCode: 'MY',
    name: 'Malaysia',
    complianceGroup: 'Malaysia',
    regionCategory: 'APAC',
    defaultDisplayCurrency: 'MYR',
    defaultCurrency: 'MYR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'ms-MY',
    supportedLanguageTags: ['ms-MY', 'en-MY'],
    defaultTimezone: 'Asia/Kuala_Lumpur',
    timezoneDefault: 'Asia/Kuala_Lumpur',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'ID',
    countryCode: 'ID',
    name: 'Indonesia',
    complianceGroup: 'Indonesia',
    regionCategory: 'APAC',
    defaultDisplayCurrency: 'IDR',
    defaultCurrency: 'IDR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'id-ID',
    supportedLanguageTags: ['id-ID', 'en-ID'],
    defaultTimezone: 'Asia/Jakarta',
    timezoneDefault: 'Asia/Jakarta',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'VN',
    countryCode: 'VN',
    name: 'Vietnam',
    complianceGroup: 'Vietnam',
    regionCategory: 'APAC',
    defaultDisplayCurrency: 'VND',
    defaultCurrency: 'VND',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'vi-VN',
    supportedLanguageTags: ['vi-VN', 'en-PH'],
    defaultTimezone: 'Asia/Ho_Chi_Minh',
    timezoneDefault: 'Asia/Ho_Chi_Minh',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'JP',
    countryCode: 'JP',
    name: 'Japan',
    complianceGroup: 'Japan',
    regionCategory: 'APAC',
    defaultDisplayCurrency: 'JPY',
    defaultCurrency: 'JPY',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'ja-JP',
    supportedLanguageTags: ['ja-JP', 'en-PH'],
    defaultTimezone: 'Asia/Tokyo',
    timezoneDefault: 'Asia/Tokyo',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'KR',
    countryCode: 'KR',
    name: 'South Korea',
    complianceGroup: 'South Korea',
    regionCategory: 'APAC',
    defaultDisplayCurrency: 'KRW',
    defaultCurrency: 'KRW',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'ko-KR',
    supportedLanguageTags: ['ko-KR', 'en-PH'],
    defaultTimezone: 'Asia/Seoul',
    timezoneDefault: 'Asia/Seoul',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'IN',
    countryCode: 'IN',
    name: 'India',
    complianceGroup: 'India',
    regionCategory: 'APAC',
    defaultDisplayCurrency: 'INR',
    defaultCurrency: 'INR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'hi-IN',
    supportedLanguageTags: ['hi-IN', 'en-IN'],
    defaultTimezone: 'Asia/Kolkata',
    timezoneDefault: 'Asia/Kolkata',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'CN',
    countryCode: 'CN',
    name: 'China',
    complianceGroup: 'China',
    regionCategory: 'APAC',
    defaultDisplayCurrency: 'CNY',
    defaultCurrency: 'CNY',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'zh-Hans',
    supportedLanguageTags: ['zh-Hans', 'en-US'],
    defaultTimezone: 'Asia/Shanghai',
    timezoneDefault: 'Asia/Shanghai',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.2.0',
    isTestFixture: false,
  },
  {
    code: 'TH',
    countryCode: 'TH',
    name: 'Thailand',
    complianceGroup: 'Thailand',
    regionCategory: 'APAC',
    defaultDisplayCurrency: 'THB',
    defaultCurrency: 'THB',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'th-TH',
    supportedLanguageTags: ['th-TH', 'en-US'],
    defaultTimezone: 'Asia/Bangkok',
    timezoneDefault: 'Asia/Bangkok',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.2.0',
    isTestFixture: false,
  },
  {
    code: 'AE',
    countryCode: 'AE',
    name: 'United Arab Emirates',
    complianceGroup: 'United Arab Emirates',
    regionCategory: 'EMEA',
    defaultDisplayCurrency: 'AED',
    defaultCurrency: 'AED',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'ar-AE',
    supportedLanguageTags: ['ar-AE', 'en-PH'],
    defaultTimezone: 'Asia/Dubai',
    timezoneDefault: 'Asia/Dubai',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'BR',
    countryCode: 'BR',
    name: 'Brazil',
    complianceGroup: 'Brazil',
    regionCategory: 'AMERICAS',
    defaultDisplayCurrency: 'BRL',
    defaultCurrency: 'BRL',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'pt-BR',
    supportedLanguageTags: ['pt-BR', 'en-PH'],
    defaultTimezone: 'America/Sao_Paulo',
    timezoneDefault: 'America/Sao_Paulo',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },

  // European Union / EEA Individual Member States (mapped to complianceGroup: 'European Union / EEA')
  {
    code: 'DE',
    countryCode: 'DE',
    name: 'Germany',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'de-DE',
    supportedLanguageTags: ['de-DE', 'en-PH'],
    defaultTimezone: 'Europe/Berlin',
    timezoneDefault: 'Europe/Berlin',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'FR',
    countryCode: 'FR',
    name: 'France',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'fr-FR',
    supportedLanguageTags: ['fr-FR', 'en-PH'],
    defaultTimezone: 'Europe/Paris',
    timezoneDefault: 'Europe/Paris',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'IT',
    countryCode: 'IT',
    name: 'Italy',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'it-IT',
    supportedLanguageTags: ['it-IT', 'en-PH'],
    defaultTimezone: 'Europe/Rome',
    timezoneDefault: 'Europe/Rome',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'ES',
    countryCode: 'ES',
    name: 'Spain',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'es-ES',
    supportedLanguageTags: ['es-ES', 'en-PH'],
    defaultTimezone: 'Europe/Madrid',
    timezoneDefault: 'Europe/Madrid',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'NL',
    countryCode: 'NL',
    name: 'Netherlands',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'nl-NL',
    supportedLanguageTags: ['nl-NL', 'en-PH'],
    defaultTimezone: 'Europe/Amsterdam',
    timezoneDefault: 'Europe/Amsterdam',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.0.0',
    isTestFixture: false,
  },
  {
    code: 'BE',
    countryCode: 'BE',
    name: 'Belgium',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'nl-NL',
    supportedLanguageTags: ['nl-NL', 'fr-FR', 'en-PH'],
    defaultTimezone: 'Europe/Brussels',
    timezoneDefault: 'Europe/Brussels',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'AT',
    countryCode: 'AT',
    name: 'Austria',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'de-DE',
    supportedLanguageTags: ['de-DE', 'en-PH'],
    defaultTimezone: 'Europe/Vienna',
    timezoneDefault: 'Europe/Vienna',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'IE',
    countryCode: 'IE',
    name: 'Ireland',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'en-GB',
    supportedLanguageTags: ['en-GB', 'ga-IE', 'en-PH'],
    defaultTimezone: 'Europe/Dublin',
    timezoneDefault: 'Europe/Dublin',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'PT',
    countryCode: 'PT',
    name: 'Portugal',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'pt-PT',
    supportedLanguageTags: ['pt-PT', 'pt-BR', 'en-PH'],
    defaultTimezone: 'Europe/Lisbon',
    timezoneDefault: 'Europe/Lisbon',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'PL',
    countryCode: 'PL',
    name: 'Poland',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'PLN', // National non-EUR currency
    defaultCurrency: 'PLN',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'pl-PL',
    supportedLanguageTags: ['pl-PL', 'en-PH'],
    defaultTimezone: 'Europe/Warsaw',
    timezoneDefault: 'Europe/Warsaw',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'SE',
    countryCode: 'SE',
    name: 'Sweden',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'SEK', // National non-EUR currency
    defaultCurrency: 'SEK',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'sv-SE',
    supportedLanguageTags: ['sv-SE', 'en-PH'],
    defaultTimezone: 'Europe/Stockholm',
    timezoneDefault: 'Europe/Stockholm',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'DK',
    countryCode: 'DK',
    name: 'Denmark',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'DKK', // National non-EUR currency
    defaultCurrency: 'DKK',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'da-DK',
    supportedLanguageTags: ['da-DK', 'en-GB', 'en-PH'],
    defaultTimezone: 'Europe/Copenhagen',
    timezoneDefault: 'Europe/Copenhagen',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'FI',
    countryCode: 'FI',
    name: 'Finland',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'fi-FI',
    supportedLanguageTags: ['fi-FI', 'sv-SE', 'en-PH'],
    defaultTimezone: 'Europe/Helsinki',
    timezoneDefault: 'Europe/Helsinki',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'GR',
    countryCode: 'GR',
    name: 'Greece',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'el-GR',
    supportedLanguageTags: ['el-GR', 'en-GB', 'en-PH'],
    defaultTimezone: 'Europe/Athens',
    timezoneDefault: 'Europe/Athens',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'CZ',
    countryCode: 'CZ',
    name: 'Czech Republic',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'CZK', // National non-EUR currency
    defaultCurrency: 'CZK',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'cs-CZ',
    supportedLanguageTags: ['cs-CZ', 'en-GB', 'en-PH'],
    defaultTimezone: 'Europe/Prague',
    timezoneDefault: 'Europe/Prague',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'RO',
    countryCode: 'RO',
    name: 'Romania',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'RON', // National non-EUR currency
    defaultCurrency: 'RON',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'ro-RO',
    supportedLanguageTags: ['ro-RO', 'en-GB', 'en-PH'],
    defaultTimezone: 'Europe/Bucharest',
    timezoneDefault: 'Europe/Bucharest',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'HU',
    countryCode: 'HU',
    name: 'Hungary',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'HUF', // National non-EUR currency
    defaultCurrency: 'HUF',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'hu-HU',
    supportedLanguageTags: ['hu-HU', 'en-GB', 'en-PH'],
    defaultTimezone: 'Europe/Budapest',
    timezoneDefault: 'Europe/Budapest',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'NO',
    countryCode: 'NO',
    name: 'Norway',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'NOK', // EEA non-EUR currency
    defaultCurrency: 'NOK',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'nb-NO',
    supportedLanguageTags: ['nb-NO', 'en-GB', 'en-PH'],
    defaultTimezone: 'Europe/Oslo',
    timezoneDefault: 'Europe/Oslo',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'IS',
    countryCode: 'IS',
    name: 'Iceland',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'is-IS',
    supportedLanguageTags: ['is-IS', 'en-GB', 'en-PH'],
    defaultTimezone: 'Atlantic/Reykjavik',
    timezoneDefault: 'Atlantic/Reykjavik',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'LU',
    countryCode: 'LU',
    name: 'Luxembourg',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'fr-FR',
    supportedLanguageTags: ['fr-FR', 'de-DE', 'en-PH'],
    defaultTimezone: 'Europe/Luxembourg',
    timezoneDefault: 'Europe/Luxembourg',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'BG',
    countryCode: 'BG',
    name: 'Bulgaria',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'bg-BG',
    supportedLanguageTags: ['bg-BG', 'en-GB', 'en-PH'],
    defaultTimezone: 'Europe/Sofia',
    timezoneDefault: 'Europe/Sofia',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'HR',
    countryCode: 'HR',
    name: 'Croatia',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'hr-HR',
    supportedLanguageTags: ['hr-HR', 'en-GB', 'en-PH'],
    defaultTimezone: 'Europe/Zagreb',
    timezoneDefault: 'Europe/Zagreb',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'CY',
    countryCode: 'CY',
    name: 'Cyprus',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'el-GR',
    supportedLanguageTags: ['el-GR', 'en-GB', 'en-PH'],
    defaultTimezone: 'Asia/Nicosia',
    timezoneDefault: 'Asia/Nicosia',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'EE',
    countryCode: 'EE',
    name: 'Estonia',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'et-EE',
    supportedLanguageTags: ['et-EE', 'en-GB', 'en-PH'],
    defaultTimezone: 'Europe/Tallinn',
    timezoneDefault: 'Europe/Tallinn',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'LV',
    countryCode: 'LV',
    name: 'Latvia',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'lv-LV',
    supportedLanguageTags: ['lv-LV', 'en-GB', 'en-PH'],
    defaultTimezone: 'Europe/Riga',
    timezoneDefault: 'Europe/Riga',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'LT',
    countryCode: 'LT',
    name: 'Lithuania',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'lt-LT',
    supportedLanguageTags: ['lt-LT', 'en-GB', 'en-PH'],
    defaultTimezone: 'Europe/Vilnius',
    timezoneDefault: 'Europe/Vilnius',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'MT',
    countryCode: 'MT',
    name: 'Malta',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'en-GB',
    supportedLanguageTags: ['en-GB', 'mt-MT', 'en-PH'],
    defaultTimezone: 'Europe/Malta',
    timezoneDefault: 'Europe/Malta',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'SK',
    countryCode: 'SK',
    name: 'Slovakia',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'sk-SK',
    supportedLanguageTags: ['sk-SK', 'en-GB', 'en-PH'],
    defaultTimezone: 'Europe/Bratislava',
    timezoneDefault: 'Europe/Bratislava',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'SI',
    countryCode: 'SI',
    name: 'Slovenia',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'EUR',
    defaultCurrency: 'EUR',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'sl-SI',
    supportedLanguageTags: ['sl-SI', 'en-GB', 'en-PH'],
    defaultTimezone: 'Europe/Ljubljana',
    timezoneDefault: 'Europe/Ljubljana',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
  {
    code: 'LI',
    countryCode: 'LI',
    name: 'Liechtenstein',
    complianceGroup: 'European Union / EEA',
    regionCategory: 'EU_EEA',
    defaultDisplayCurrency: 'CHF', // EEA non-EUR currency
    defaultCurrency: 'CHF',
    allowedDisplayCurrencies: GLOBAL_SUPPORTED_CURRENCY_CODES,
    allowedChargeCurrencies: ['PHP'],
    defaultLanguageTag: 'de-DE',
    supportedLanguageTags: ['de-DE', 'en-PH'],
    defaultTimezone: 'Europe/Vaduz',
    timezoneDefault: 'Europe/Vaduz',
    unitSystem: 'metric',
    isActive: true,
    enabled: true,
    effectiveFrom: '2026-01-01T00:00:00.000Z',
    configVersion: '1.1.0',
    isTestFixture: false,
  },
]);

export const GLOBAL_SUPPORTED_COUNTRY_CODES: readonly string[] = Object.freeze(
  GLOBAL_COUNTRY_CATALOG.map(c => c.code)
);

/**
 * Retrieves country profile by ISO 3166-1 alpha-2 code.
 */
export function getCountryProfile(code: string): GlobalCountryProfile | null {
  if (!code || typeof code !== 'string') return null;
  const upper = code.trim().toUpperCase();
  return GLOBAL_COUNTRY_CATALOG.find(c => c.code === upper) ?? null;
}

/**
 * Checks if a country code is supported in the global catalog.
 */
export function isSupportedCountryCode(code: string): boolean {
  if (!code || typeof code !== 'string') return false;
  const upper = code.trim().toUpperCase();
  return GLOBAL_SUPPORTED_COUNTRY_CODES.includes(upper);
}

/**
 * Returns all country profiles that map to a specific compliance jurisdiction/group.
 */
export function getCountriesByComplianceGroup(complianceGroup: string): readonly GlobalCountryProfile[] {
  const norm = complianceGroup.trim().toLowerCase();
  return GLOBAL_COUNTRY_CATALOG.filter(c => c.complianceGroup.toLowerCase() === norm);
}
