'use server';

import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/ai/ai-logger';
import { SocialCommandLayer } from '@/lib/social/social-command-layer';
import { logSocialAction } from '@/lib/social/social-logger';
import { revalidatePath } from 'next/cache';

import { redirect } from 'next/navigation';

async function checkAdminAuth() {
  const session = await getServerSession(authOptions);
  const user = session?.user as any;
  if (!user || (user.role !== 'Admin' && user.role !== 'Super Admin')) {
    throw new Error('Unauthorized');
  }
  return user;
}

export async function createCampaign(formData: FormData) {
  const user = await checkAdminAuth();
  
  const name = formData.get('campaign_name') as string;
  const type = formData.get('campaign_type') as string;
  const goal = formData.get('campaign_goal') as string;
  
  const campaign = await prisma.marketingCampaign.create({
    data: {
      campaign_name: name,
      campaign_type: type,
      campaign_goal: goal,
      campaign_status: 'Draft',
      approval_status: 'Draft',
      created_by_id: user.id
    }
  });

  await logSocialAction({
    userId: user.id,
    action: 'CAMPAIGN_CREATED',
    campaignId: campaign.id,
    details: `Created campaign: ${name}`
  });

  revalidatePath('/dashboard/admin/marketing/campaigns');
  redirect(`/dashboard/admin/marketing/campaigns/${campaign.id}`);
}

export async function createMarketingPost(campaignId: string, platform: string, caption: string) {
  const user = await checkAdminAuth();

  const post = await prisma.marketingPost.create({
    data: {
      campaign_id: campaignId,
      platform,
      caption,
      post_type: 'Text',
      post_status: 'Generated by AI',
      approval_status: 'Draft',
      created_by_id: user.id
    }
  });

  await logSocialAction({
    userId: user.id,
    action: 'POST_GENERATED',
    postId: post.id,
    campaignId,
    details: `Generated post for ${platform}`
  });

  revalidatePath(`/dashboard/admin/marketing/campaigns/${campaignId}`);
  return post;
}

export async function submitPostForApproval(postId: string) {
  const user = await checkAdminAuth();
  await SocialCommandLayer.requestApproval(postId, user.id);
  revalidatePath('/dashboard/admin/marketing');
  return { success: true };
}

export async function approvePostAction(postId: string) {
  const user = await checkAdminAuth();
  await SocialCommandLayer.approvePost(postId, user.id, user.role);
  revalidatePath('/dashboard/admin/marketing');
  return { success: true };
}

export async function rejectPostAction(postId: string, reason: string) {
  const user = await checkAdminAuth();
  await prisma.marketingPost.update({
    where: { id: postId },
    data: {
      post_status: 'Rejected',
      approval_status: 'Rejected',
      rejection_reason: reason
    }
  });

  await logSocialAction({
    userId: user.id,
    action: 'POST_REJECTED',
    postId,
    details: `Rejected: ${reason}`
  });

  revalidatePath('/dashboard/admin/marketing');
  return { success: true };
}

export async function mockPublishAction(postId: string) {
  const user = await checkAdminAuth();
  const result = await SocialCommandLayer.publishNow(postId, user.id);
  revalidatePath('/dashboard/admin/marketing');
  return result;
}
