const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const appsApiDir = path.join(rootDir, 'apps', 'api');

// Create directories
fs.mkdirSync(path.join(appsApiDir, 'src', 'middleware'), { recursive: true });
fs.mkdirSync(path.join(appsApiDir, 'src', 'routes'), { recursive: true });
fs.mkdirSync(path.join(appsApiDir, 'src', 'services'), { recursive: true });

// 1. paymongoSignature.ts
fs.writeFileSync(path.join(appsApiDir, 'src', 'middleware', 'paymongoSignature.ts'), [
  "import { Request, Response, NextFunction } from 'express';",
  "import crypto from 'crypto';",
  "",
  "export const verifyPaymongoSignature = (req: Request, res: Response, next: NextFunction) => {",
  "  const signatureHeader = req.headers['paymongo-signature'] as string;",
  "  if (!signatureHeader) {",
  "    return res.status(401).json({ error: 'Missing PayMongo signature' });",
  "  }",
  "",
  "  // Extract timestamp (t) and signature (te or v1)",
  "  const parts = signatureHeader.split(',');",
  "  const t = parts.find(p => p.startsWith('t='))?.split('=')[1];",
  "  const te = parts.find(p => p.startsWith('te='))?.split('=')[1] || parts.find(p => p.startsWith('v1='))?.split('=')[1];",
  "",
  "  if (!t || !te) {",
  "    return res.status(401).json({ error: 'Invalid PayMongo signature format' });",
  "  }",
  "",
  "  const webhookSecret = process.env.PAYMONGO_WEBHOOK_SECRET;",
  "  if (!webhookSecret) {",
  "    console.error('PAYMONGO_WEBHOOK_SECRET is not configured');",
  "    return res.status(500).json({ error: 'Webhook configuration error' });",
  "  }",
  "",
  "  // Reconstruct payload and hash",
  "  // NOTE: This assumes req.body has NOT been parsed to JSON yet, or we have rawBody access.",
  "  // For production, express.raw({type: 'application/json'}) is required before this middleware.",
  "  const payload = \`\${t}.\${(req as any).rawBody || JSON.stringify(req.body)}\`;",
  "  const expectedSignature = crypto.createHmac('sha256', webhookSecret).update(payload).digest('hex');",
  "",
  "  if (expectedSignature !== te) {",
  "    return res.status(401).json({ error: 'Webhook signature verification failed' });",
  "  }",
  "",
  "  next();",
  "};"
].join('\\n'));

// 2. ledgerService.ts
fs.writeFileSync(path.join(appsApiDir, 'src', 'services', 'ledgerService.ts'), [
  "import { PrismaClient } from '@prisma/client';",
  "const prisma = new PrismaClient();",
  "",
  "// Phase 7: Immutable Double-Entry Financial Ledger",
  "export const postPaymentSuccess = async (",
  "  bookingId: string,",
  "  paymongoIntentId: string,",
  "  totalPaid: number,",
  "  platformFee: number,",
  "  providerShare: number,",
  "  depositAmount: number",
  ") => {",
  "  return await prisma.$transaction(async (tx) => {",
  "    // 1. Idempotency Check to prevent duplicate posting",
  "    const existingLedger = await tx.financeLedger.findFirst({",
  "      where: { transaction_reference: paymongoIntentId }",
  "    });",
  "",
  "    if (existingLedger) {",
  "      console.log('Payment already posted to ledger. Skipping idempotent request.');",
  "      return;",
  "    }",
  "",
  "    const booking = await tx.booking.findUnique({",
  "      where: { id: bookingId },",
  "      include: { listing: true }",
  "    });",
  "",
  "    if (!booking) throw new Error('Booking not found');",
  "",
  "    // 2. Update Booking Status",
  "    await tx.booking.update({",
  "      where: { id: bookingId },",
  "      data: { status: 'PAID' }",
  "    });",
  "",
  "    // 3. Post to Ledger",
  "    await tx.financeLedger.create({",
  "      data: {",
  "        booking_id: bookingId,",
  "        user_id: booking.renter_id,",
  "        provider_id: booking.listing.provider_id,",
  "        transaction_reference: paymongoIntentId,",
  "        total_amount: totalPaid,",
  "        platform_fee: platformFee,",
  "        provider_payable: providerShare,",
  "        deposit_held: depositAmount,",
  "        transaction_type: 'PAYMENT_SUCCESS',",
  "        status: 'CLEARED'",
  "      }",
  "    });",
  "  });",
  "};"
].join('\\n'));

// 3. webhooks.ts
fs.writeFileSync(path.join(appsApiDir, 'src', 'routes', 'webhooks.ts'), [
  "import { Router } from 'express';",
  "import { verifyPaymongoSignature } from '../middleware/paymongoSignature';",
  "import { postPaymentSuccess } from '../services/ledgerService';",
  "",
  "const router = Router();",
  "",
  "router.post('/paymongo', verifyPaymongoSignature, async (req, res) => {",
  "  try {",
  "    const event = req.body;",
  "",
  "    // Idempotent webhook processing",
  "    if (event.data.attributes.type === 'payment.paid') {",
  "      const paymentIntent = event.data.attributes.data.attributes;",
  "      const metadata = paymentIntent.metadata;",
  "      ",
  "      // Platform fee logic (e.g., 10%)",
  "      const totalPaid = paymentIntent.amount / 100;",
  "      const depositAmount = metadata?.depositAmount ? parseFloat(metadata.depositAmount) : 0;",
  "      const baseRental = totalPaid - depositAmount;",
  "      const platformFee = baseRental * 0.10;",
  "      const providerShare = baseRental - platformFee;",
  "",
  "      await postPaymentSuccess(",
  "        metadata.bookingId,",
  "        event.data.id, // paymongoIntentId as Idempotency Key",
  "        totalPaid,",
  "        platformFee,",
  "        providerShare,",
  "        depositAmount",
  "      );",
  "    }",
  "",
  "    res.status(200).send('Webhook processed');",
  "  } catch (error: any) {",
  "    console.error('Webhook processing failed:', error);",
  "    // Always return 200 to prevent webhook retries on our business logic errors, ",
  "    // unless it is a transient DB connection issue.",
  "    res.status(200).send('Webhook acknowledged with errors');",
  "  }",
  "});",
  "",
  "export default router;"
].join('\\n'));

console.log("Phase 7 Payments and Ledger scaffolded.");
