import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const POLICY_VERSION = "PH-V1.0";

const seedData = [
  {
    policyCode: "PI-001",
    name: "Illegal Drugs and Controlled Substances",
    slug: "illegal-drugs",
    summary: "Illegal drugs, controlled precursors, and drug paraphernalia.",
    fullDescription: "Shabu, Methamphetamine, Cocaine, Heroin, Ecstasy, Illegal cannabis, Marijuana, THC products, Controlled precursors, Drug-making chemicals, Drug-manufacturing equipment, Drug paraphernalia, Synthetic illegal drugs, Drug delivery services.",
    classification: "PROHIBITED",
    riskLevel: "CRITICAL",
    enforcementAction: "BLOCK",
    examples: "Shabu, Cocaine, Heroin, Marijuana, Bongs, Pipes",
    prohibitedKeywords: "shabu, methamphetamine, cocaine, heroin, ecstasy, weed, marijuana, cannabis, thc, bong",
    reviewKeywords: "pipe, precursor",
    exclusions: "Lawful hemp products with THC < 0.3%",
  },
  {
    policyCode: "PI-002",
    name: "Medicines, Health Products and Medical Substances",
    slug: "medicines-health-products",
    summary: "Prescription medicines, unverified health products, and dangerous substances.",
    fullDescription: "Prescription medicines, Pharmacy-only medicines, Controlled medicines, Vaccines, Biologicals, Blood products, Injectable products, Unregistered supplements, Unauthorized therapeutic products.",
    classification: "PROHIBITED",
    riskLevel: "CRITICAL",
    enforcementAction: "BLOCK",
    examples: "Prescription medicine, Antibiotics, Mercury thermometers",
    prohibitedKeywords: "prescription medicine, antibiotics, mercury thermometer, abortion drug, counterfeit medicine",
    reviewKeywords: "supplement, medical device",
    exclusions: "Over-the-counter vitamins (requires review)",
  },
  {
    policyCode: "PI-003",
    name: "Firearms, Ammunition, Weapons and Explosives",
    slug: "firearms-weapons",
    summary: "Firearms, explosives, and illegal weapons.",
    fullDescription: "Firearms, Ammunition, Bullets, Cartridges, Primers, Receivers, Frames, Barrels, Major firearm components, Silencers, Suppressors, Conversion kits, Bombs, Grenades, Improvised explosive devices, Fireworks, Pyrotechnics, Tasers, Switchblades.",
    classification: "PROHIBITED",
    riskLevel: "CRITICAL",
    enforcementAction: "BLOCK",
    examples: "Gun, Pistol, Rifle, Bullets, Taser, Switchblade",
    prohibitedKeywords: "baril, bala, ammunition, firearm, taser, switchblade, grenade, bomb, explosive",
    reviewKeywords: "airsoft, pellet",
    exclusions: "Kitchen knives, Martial arts equipment for training",
  },
  {
    policyCode: "PI-004",
    name: "Hazardous Chemicals, Toxic Materials and Waste",
    slug: "hazardous-chemicals",
    summary: "Dangerous chemicals and radioactive materials.",
    fullDescription: "Poison, Toxic substances, Mercury, Cyanide, Asbestos, Industrial acids, Corrosive chemicals, Hazardous pesticides, Fumigants, Chemical warfare agents, Dangerous biological agents, Radioactive materials.",
    classification: "PROHIBITED",
    riskLevel: "CRITICAL",
    enforcementAction: "BLOCK",
    examples: "Cyanide, Mercury, Asbestos",
    prohibitedKeywords: "poison, mercury, cyanide, asbestos, radioactive",
    reviewKeywords: "acid, chemical",
    exclusions: "Household cleaning products",
  },
  {
    policyCode: "PI-005",
    name: "Alcohol, Tobacco, Nicotine and Vape Products",
    slug: "alcohol-tobacco-vape",
    summary: "Alcohol and nicotine products.",
    fullDescription: "Beer, Wine, Liquor, Alcoholic beverages, Cigarettes, Cigars, Loose tobacco, Heated tobacco, Electronic cigarettes, Vape devices, E-liquid, Vape juice, Nicotine pouches, Nicotine liquids.",
    classification: "PROHIBITED",
    riskLevel: "HIGH",
    enforcementAction: "BLOCK",
    examples: "Beer, Wine, Cigarettes, Vape",
    prohibitedKeywords: "vape, e-liquid, cigarette, tobacco, liquor, beer, wine",
    reviewKeywords: "nicotine",
    exclusions: "Empty collectible bottles (requires review)",
  },
  {
    policyCode: "PI-006",
    name: "Human Bodies, Remains and Biological Materials",
    slug: "human-biological-materials",
    summary: "Human organs and biological materials.",
    fullDescription: "Human organs, Human body parts, Human remains, Human ashes, Human tissue, Blood, Plasma, Semen, Ova, Embryos, Human biological samples, Human teeth, Human bones.",
    classification: "PROHIBITED",
    riskLevel: "CRITICAL",
    enforcementAction: "BLOCK",
    examples: "Human organ, Blood",
    prohibitedKeywords: "human organ, human bone, blood for sale",
    reviewKeywords: "plasma",
    exclusions: "Medical training models (synthetic)",
  },
  {
    policyCode: "PI-007",
    name: "Child Exploitation and Illegal Sexual Material",
    slug: "illegal-sexual-material",
    summary: "Exploitative materials and illegal sexual services.",
    fullDescription: "Child sexual abuse material, Child sexual exploitation material, Sexualized material involving minors, AI-generated sexual material depicting minors, Non-consensual intimate images, Sexual exploitation services.",
    classification: "PROHIBITED",
    riskLevel: "CRITICAL",
    enforcementAction: "ESCALATE",
    examples: "CSAM, Illegal escort services",
    prohibitedKeywords: "escort, prostitution, illegal sexual service",
    reviewKeywords: "massage",
    exclusions: "None",
  },
  {
    policyCode: "PI-008",
    name: "Wildlife, Protected Species and Animal Products",
    slug: "wildlife-animal-products",
    summary: "Protected species, ivory, and illegal animal products.",
    fullDescription: "Endangered wildlife, Threatened wildlife, Protected wildlife, Wild-caught animals, Invasive species, Ivory, Rhino horn, Protected coral, Turtle shell, Wildlife skins, Feathers, Bones, Teeth.",
    classification: "PROHIBITED",
    riskLevel: "CRITICAL",
    enforcementAction: "BLOCK",
    examples: "Ivory, Rhino horn, Live exotic animals",
    prohibitedKeywords: "ivory, rhino horn, pangolin, protected wildlife",
    reviewKeywords: "exotic pet, taxidermy",
    exclusions: "Antiques with documentation (requires review)",
  },
  {
    policyCode: "PI-009",
    name: "Agricultural Chemicals, Plants, Seeds and Forest Products",
    slug: "agricultural-forest-products",
    summary: "Unregistered pesticides and illegal lumber.",
    fullDescription: "Unregistered pesticides, Restricted pesticides, Unlicensed fertilizers, Restricted herbicides, Genetically modified seeds without authorization, Illegally harvested timber, Illegal logs, Illegal lumber.",
    classification: "PROHIBITED",
    riskLevel: "HIGH",
    enforcementAction: "BLOCK",
    examples: "Illegal lumber, Unregistered pesticide",
    prohibitedKeywords: "illegal lumber, illegal logging, unregistered pesticide",
    reviewKeywords: "fertilizer, seed, lumber",
    exclusions: "Registered garden fertilizers",
  },
  {
    policyCode: "PI-010",
    name: "Unsafe, Prohibited or Deceptively Marketed Food",
    slug: "unsafe-food",
    summary: "Contaminated or deceptively marketed food.",
    fullDescription: "Adulterated food, Contaminated food, Poisonous food, Expired food, Food with altered expiry dates, Illegally repacked food, Counterfeit food.",
    classification: "PROHIBITED",
    riskLevel: "HIGH",
    enforcementAction: "BLOCK",
    examples: "Expired food, Repacked dairy",
    prohibitedKeywords: "expired food, repacked food, wild mushroom",
    reviewKeywords: "homemade food",
    exclusions: "Commercially sealed safe food items (if allowed by platform)",
  },
  {
    policyCode: "PI-011",
    name: "Counterfeit, Pirated and IP-Infringing Goods",
    slug: "counterfeit-pirated-goods",
    summary: "Fake products and pirated media.",
    fullDescription: "Fake branded products, Unauthorized replicas, Counterfeit spare parts, Pirated movies, Pirated software, Pirated games, Pirated music, Unauthorized software keys.",
    classification: "PROHIBITED",
    riskLevel: "HIGH",
    enforcementAction: "BLOCK",
    examples: "Fake bags, Pirated software",
    prohibitedKeywords: "counterfeit, fake branded, replica, pirated software, bootleg",
    reviewKeywords: "inspired by, copy",
    exclusions: "Generic unbranded items",
  },
  {
    policyCode: "PI-012",
    name: "Stolen, Smuggled or Unlawfully Obtained Property",
    slug: "stolen-property",
    summary: "Stolen and smuggled goods.",
    fullDescription: "Stolen goods, Looted property, Smuggled goods, Embargoed goods, Items with removed serial numbers, Vehicles with tampered VINs.",
    classification: "PROHIBITED",
    riskLevel: "CRITICAL",
    enforcementAction: "BLOCK",
    examples: "Stolen phone, Smuggled electronics",
    prohibitedKeywords: "stolen, smuggled, altered serial",
    reviewKeywords: "no box, unverified",
    exclusions: "Second-hand goods with proof of purchase",
  },
  {
    policyCode: "PI-013",
    name: "Recalled, Expired, Unsafe or Deceptively Labelled Goods",
    slug: "unsafe-recalled-goods",
    summary: "Recalled products and unsafe equipment.",
    fullDescription: "Recalled products, Expired products, Mislabelled products, Damaged safety equipment, Defective products presenting imminent danger.",
    classification: "PROHIBITED",
    riskLevel: "HIGH",
    enforcementAction: "BLOCK",
    examples: "Recalled car seat, Damaged helmet",
    prohibitedKeywords: "recalled product, damaged safety equipment",
    reviewKeywords: "expired, broken",
    exclusions: "Cosmetically flawed but safe items",
  },
  {
    policyCode: "PI-014",
    name: "Currency, Financial Instruments and Financial Services",
    slug: "currency-financial",
    summary: "Counterfeit currency and unregulated financial services.",
    fullDescription: "Counterfeit currency, Checks, Money orders, Credit cards, E-wallet accounts, Cryptocurrency, Unlicensed loans, Money-laundering services.",
    classification: "PROHIBITED",
    riskLevel: "CRITICAL",
    enforcementAction: "BLOCK",
    examples: "Fake money, Credit card numbers",
    prohibitedKeywords: "counterfeit currency, credit card info, bank account for sale",
    reviewKeywords: "loan, crypto",
    exclusions: "Collectible antique coins",
  },
  {
    policyCode: "PI-015",
    name: "Gambling Products and Services",
    slug: "gambling",
    summary: "Lottery tickets and betting services.",
    fullDescription: "Lottery tickets, Betting slips, Gambling accounts, Casino credits, Slot machines, Match-fixing services, Unlicensed betting.",
    classification: "PROHIBITED",
    riskLevel: "HIGH",
    enforcementAction: "BLOCK",
    examples: "Lottery ticket, Slot machine",
    prohibitedKeywords: "lottery ticket, slot machine, casino credit",
    reviewKeywords: "bet, gamble",
    exclusions: "Board games, Playing cards",
  },
  {
    policyCode: "PI-016",
    name: "Government, Police and Military Property or Credentials",
    slug: "government-credentials",
    summary: "Fake IDs and government property.",
    fullDescription: "Government identification cards, Passports, Visas, Driver’s licences, Police badges, Military badges, Official uniforms, Fake permits.",
    classification: "PROHIBITED",
    riskLevel: "CRITICAL",
    enforcementAction: "BLOCK",
    examples: "Fake ID, Passport for sale, Police badge",
    prohibitedKeywords: "fake id, passport for sale, police badge, fake permit",
    reviewKeywords: "uniform, badge",
    exclusions: "Historical military memorabilia (demilitarized)",
  },
  {
    policyCode: "PI-017",
    name: "Surveillance, Interception and Illegal Telecommunications Devices",
    slug: "surveillance-devices",
    summary: "Signal jammers and wiretapping devices.",
    fullDescription: "Signal jammers, Unauthorized repeaters, Wiretapping devices, Telephone bugs, Hidden recording devices marketed for illegal surveillance, Cable descramblers.",
    classification: "PROHIBITED",
    riskLevel: "CRITICAL",
    enforcementAction: "BLOCK",
    examples: "Signal jammer, Spy camera",
    prohibitedKeywords: "signal jammer, wiretap, hidden recording device, descrambler",
    reviewKeywords: "spy, surveillance",
    exclusions: "Standard CCTV cameras, Baby monitors",
  },
  {
    policyCode: "PI-018",
    name: "Malicious Digital Products and Stolen Information",
    slug: "malicious-digital",
    summary: "Malware, hacked accounts, and stolen data.",
    fullDescription: "Malware, Ransomware, Computer viruses, Spyware, Credential-stealing software, Botnets, Denial-of-service services, Phishing kits, Stolen usernames, Hacked accounts.",
    classification: "PROHIBITED",
    riskLevel: "CRITICAL",
    enforcementAction: "BLOCK",
    examples: "Ransomware, Hacked Netflix account",
    prohibitedKeywords: "malware, ransomware, spyware, hacked account, stolen password",
    reviewKeywords: "hack, exploit",
    exclusions: "Legitimate cybersecurity educational tools",
  },
  {
    policyCode: "PI-019",
    name: "Obscene, Hateful, Violent or Criminal Materials",
    slug: "obscene-hateful",
    summary: "Hateful materials and criminal instructions.",
    fullDescription: "Obscene materials, Terrorist recruitment materials, Violent extremist recruitment materials, Products promoting genocide, Products promoting targeted violence, Gang recruitment materials.",
    classification: "PROHIBITED",
    riskLevel: "HIGH",
    enforcementAction: "BLOCK",
    examples: "Terrorist propaganda, Extremist manuals",
    prohibitedKeywords: "terrorist recruitment, hate crime promotion, gang recruitment",
    reviewKeywords: "extremist, violent",
    exclusions: "Historical discussion, Journalism",
  },
  {
    policyCode: "PI-020",
    name: "Cultural Property, Antiquities and Archaeological Materials",
    slug: "cultural-property",
    summary: "Illegally obtained cultural property.",
    fullDescription: "Illegally obtained antiquities, Archaeological materials, Protected historical relics, Protected cultural property, Sacred cultural objects obtained without authority, Stolen artworks.",
    classification: "PROHIBITED",
    riskLevel: "HIGH",
    enforcementAction: "BLOCK",
    examples: "Looted artifact, Stolen artwork",
    prohibitedKeywords: "looted antiquity, stolen artwork, illegal artifact",
    reviewKeywords: "relic, archaeological",
    exclusions: "Legitimate antiques with provenance",
  },
  {
    policyCode: "PI-021",
    name: "Precious Materials and Conflict Goods",
    slug: "conflict-goods",
    summary: "Conflict minerals and illegally mined metals.",
    fullDescription: "Unverified bullion, Conflict diamonds, Conflict minerals, Illegally mined minerals, Regulated mine tailings, Precious metals without lawful provenance.",
    classification: "PROHIBITED",
    riskLevel: "HIGH",
    enforcementAction: "BLOCK",
    examples: "Conflict diamond, Unverified bullion",
    prohibitedKeywords: "conflict diamond, illegal gold, unverified bullion",
    reviewKeywords: "bullion, rough diamond",
    exclusions: "Verified jewelry",
  },
  {
    policyCode: "PI-022",
    name: "Chainsaws and Specially Regulated Equipment",
    slug: "regulated-equipment",
    summary: "Chainsaws and regulated tools.",
    fullDescription: "Chainsaws, Chainsaw engines, Chainsaw bars, Critical chainsaw components, Equipment intended for illegal logging, Unauthorized media-manufacturing equipment, Radioactive measuring equipment.",
    classification: "PROHIBITED",
    riskLevel: "HIGH",
    enforcementAction: "BLOCK",
    examples: "Chainsaw, Logging equipment",
    prohibitedKeywords: "chainsaw, illegal logging equipment",
    reviewKeywords: "power tool, engine",
    exclusions: "Standard DIY power tools (e.g., drills)",
  },
  {
    policyCode: "PI-023",
    name: "Fraud, Forgery and Impersonation Materials",
    slug: "fraud-forgery",
    summary: "Fake diplomas and forgery tools.",
    fullDescription: "Fake diplomas, Fake transcripts, Fake employment certificates, Fake medical certificates, Forged receipts, Fake event tickets, Unauthorized master keys, Odometer-altering devices.",
    classification: "PROHIBITED",
    riskLevel: "CRITICAL",
    enforcementAction: "BLOCK",
    examples: "Fake degree, Odometer rollback tool",
    prohibitedKeywords: "fake diploma, forged receipt, odometer rollback, unauthorized master key",
    reviewKeywords: "ticket, certificate",
    exclusions: "Novelty joke certificates (clearly marked)",
  },
  {
    policyCode: "PI-024",
    name: "Illegal or Exploitative Services",
    slug: "illegal-services",
    summary: "Human trafficking and illegal services.",
    fullDescription: "Human trafficking, Sexual services, Contract violence, Intimidation services, Illegal debt collection, Document forgery, Hacking-for-hire, Smuggling, Illegal gambling.",
    classification: "PROHIBITED",
    riskLevel: "CRITICAL",
    enforcementAction: "BLOCK",
    examples: "Hitman, Hacker for hire",
    prohibitedKeywords: "human trafficking, contract violence, hitman, hacking for hire, smuggling",
    reviewKeywords: "debt collection, proxy",
    exclusions: "Licensed private investigators",
  },
  {
    policyCode: "PI-025",
    name: "Catch-All Illegal, Unsafe or Unacceptable Listings",
    slug: "catch-all",
    summary: "Any listing that presents an unacceptable legal or safety risk.",
    fullDescription: "Illegal in the provider’s jurisdiction, Subject to a lawful takedown order, Dangerous, Unsafe, Fraudulent, Exploitative, Invasive of privacy, Unacceptable security risk.",
    classification: "PROHIBITED",
    riskLevel: "HIGH",
    enforcementAction: "HOLD_FOR_REVIEW",
    examples: "Unlisted dangerous chemical, New exploit tool",
    prohibitedKeywords: "illegal, exploit, bypass, unverified risk",
    reviewKeywords: "suspicious, risky",
    exclusions: "None",
  },
];

async function main() {
  console.log("Seeding Prohibited Item Policies...");
  
  for (const policy of seedData) {
    await prisma.prohibitedItemPolicy.upsert({
      where: { policyCode: policy.policyCode },
      update: {
        name: policy.name,
        slug: policy.slug,
        summary: policy.summary,
        fullDescription: policy.fullDescription,
        classification: policy.classification,
        riskLevel: policy.riskLevel,
        enforcementAction: policy.enforcementAction,
        examples: policy.examples,
        prohibitedKeywords: policy.prohibitedKeywords,
        reviewKeywords: policy.reviewKeywords,
        exclusions: policy.exclusions,
        effectiveFrom: new Date(),
        policyVersion: POLICY_VERSION,
        automaticBlockEnabled: policy.enforcementAction === "BLOCK",
        securityEscalationRequired: policy.riskLevel === "CRITICAL",
        manualReviewRequired: policy.enforcementAction === "HOLD_FOR_REVIEW",
      },
      create: {
        ...policy,
        effectiveFrom: new Date(),
        policyVersion: POLICY_VERSION,
        automaticBlockEnabled: policy.enforcementAction === "BLOCK",
        securityEscalationRequired: policy.riskLevel === "CRITICAL",
        manualReviewRequired: policy.enforcementAction === "HOLD_FOR_REVIEW",
      },
    });
  }

  console.log("Seeding complete. V1.0 policy catalog is active.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
